### ISSUE TITLE
Video File missing because Website is offline/broken link

### ISSUE THREAD

**Issue by D-VR** [lijiarui/wechaty-getting-started#11]
https://blog.wechaty.io/guide/2017/01/01/getting-started-wechaty.html
is broken. Video File no longer Available.

**Comment by lijiarui** [comment]
Thanks! 
Could you tell me where did you find the link?
It should change `wechaty` to `chatie`
Correct link: https://blog.chatie.io/guide/2017/01/01/getting-started-wechaty.html

**Comment by D-VR** [comment]
`<a target="_blank" href="https://blog.wechaty.io/guide/2017/01/01/getting-started-wechaty.html">`
in README.md.

> https://blog.chatie.io/guide/2017/01/01/getting-started-wechaty.html
also 404s
i think you mean
https://blog.chatie.io/getting-started-wechaty/

**Comment by D-VR** [comment]
Submitted Pull Request with Fixed Link

**Comment by lijiarui** [comment]
Thanks!
