### ISSUE TITLE
WARN PuppetPuppeteer initWatchdogForPuppet() dog.on(reset) last food:inited, timeout:120000

### ISSUE THREAD

**Issue by lylasi** [lijiarui/wechaty-getting-started#20]
运行刚开始正常收发信息，一会后就报这条信息，之后就不能正常使用。

MacOS node js

**Comment by zixia** [comment]
Please provide the following information so that we could be able to help you:

1. What is your Wechaty version?
1. What is the puppet you are using?
1. What's the log message when you ran into this issue? (by setting `WECHATY_LOG=silly`)

**Comment by zixia** [comment]
Merge to https://github.com/Chatie/wechaty/issues/1439

**Comment by zixia** [comment]
This issue should be fixed on Wechaty v0.17.116 or above.
